services:
  cache:
    container_name: "cache"
    restart: unless-stopped
    volumes:
      - cache:/data
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 5

  gopray:
    container_name: "gopray"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/gopray/
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      cache:
        condition: service_healthy

volumes:
  cache:
