version: "3.8"

services:
  gopray:
    container_name: "gopray"
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
