version: "3.8"

services:
  cache:
    container_name: "cache"
    restart: unless-stopped
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 5

  gopray:
    container_name: "gopray"
    restart: unless-stopped
    volumes:
      - .:/go/src/github.com/escalopa/gopray/
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CACHE_URL=${CACHE_URL}
      - DATA_PATH=${DATA_PATH}
      - TIME_LOCATION=${TIME_LOCATION}
      - UPCOMING_REMINDER=${UPCOMING_REMINDER}
      - GOMAA_NOTIFY_HOUR=${GOMAA_NOTIFY_HOUR}
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    depends_on:
      cache:
        condition: service_healthy
