version: "3.8"

services:
  kazan-bot:
    image: dekuyo/gopray:latest
    secrets:
      - gopray_kazan_bot_token
      - gopray_cache_url
    environment:
      - PORT=8080
      - OWNER_ID=1385434843

      - BOT_TOKEN_FILE=/run/secrets/gopray_bot_token
      - BOT_DATA=/go/src/github.com/escalopa/gopray/csv/kazan.csv

      - CACHE_URL_FILE=/run/secrets/gopray_cache_url
      - CACHE_PREFIX=kazan

      - LOCATION=Europe/Moscow
      - LANGUAGES_PATH=/go/src/github.com/escalopa/gopray/languages

      - UPCOMING_REMINDER=20m
      - JUMMAH_REMINDER=8h
    extra_hosts:
      - "host.docker.internal:host-gateway"

  inno-bot:
    image: dekuyo/gopray:latest
    secrets:
      - gopray_inno_bot_token
      - gopray_cache_url
    environment:
      - PORT=8080
      - OWNER_ID=1385434843

      - BOT_TOKEN_FILE=/run/secrets/gopray_bot_token
      - BOT_DATA=/go/src/github.com/escalopa/gopray/csv/innopolis.csv

      - CACHE_URL_FILE=/run/secrets/gopray_cache_url
      - CACHE_PREFIX=inno

      - LOCATION=Europe/Moscow
      - LANGUAGES_PATH=/go/src/github.com/escalopa/gopray/languages

      - UPCOMING_REMINDER=20m
      - JUMMAH_REMINDER=8h
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  gopray_kazan_bot_token:
    external: true
  gopray_inno_bot_token:
    external: true
  gopray_cache_url:
    external: true
