version: "3.8"

services:
  telegram:
    image: dekuyo/gopray:latest
    volumes:
      - .:/go/src/github.com/escalopa/gopray/
    secrets:
      - gopray_bot_token
      - gopray_cache_url
    environment:
      - BOT_TOKEN_FILE=/run/secrets/gopray_bot_token
      - BOT_OWNER_ID=1385434843

      - CACHE_URL_FILE=/run/secrets/gopray_cache_url
      - DATA_PATH=/go/src/github.com/escalopa/gopray/times.csv
      - LANGUAGES_PATH=/go/src/github.com/escalopa/gopray/languages

      - TIME_LOCATION=Europe/Moscow
      - UPCOMING_REMINDER=20m
      - GOMAA_NOTIFY_HOUR=8h
    extra_hosts:
      - "host.docker.internal:host-gateway"

secrets:
  gopray_bot_token:
    external: true
  gopray_cache_url:
    external: true
