version: "3"

tasks:
  # Build the binary & docker image & push to Docker Hub
  deploy:
    cmds:
      - echo "Building image..."
      - docker build -f ./Dockerfile -t dekuyo/gopray:${TAG} --target=production --no-cache .
      - echo "Deploying image to Docker Hub..."
      - docker image push dekuyo/gopray:${TAG}
  # Run tests
  test:
    cmds:
      - go test -coverprofile=coverage.txt  -covermode=count ./...
